services:
  experiment-service:
    build:
      context: .
      dockerfile: apps/service/Dockerfile
    image: experiment-service
    container_name: experiment-compose-service
    network_mode: host
    ports:
      - "3001:3001"

  experiment-nxcontainer:
    build:
      context: .
      dockerfile: apps/nxcontainer/Dockerfile
    image: experiment-nxcontainer
    container_name: experiment-compose-nxcontainer
    network_mode: host
    ports:
      - "3000:3000"
    depends_on:
      - experiment-service

  experiment-service-e2e:
    build:
      context: .
      dockerfile: apps/service-e2e/Dockerfile
    image: experiment-service-e2e
    container_name: experiment-container-service-e2e
    network_mode: host
    depends_on:
      - experiment-service

  experiment-nxcontainer-e2e:
    build:
      context: .
      dockerfile: apps/nxcontainer-e2e/Dockerfile
    image: experiment-nxcontainer-e2e
    container_name: experiment-container-nxcontainer-e2e
    network_mode: host
    depends_on:
      - experiment-nxcontainer
      - experiment-service-e2e
